<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H5MG9OP" failures="1" tests="3" name="Listeners" time="0.063" errors="0" timestamp="2022-03-01T22:49:35 IST">
  <testcase classname="testNGConcepts.ListenerTest" name="testFail" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGConcepts.ListenerTest.testFail(ListenerTest.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="testNGConcepts.ListenerTest" name="testPass" time="0.017"/>
  <testcase classname="testNGConcepts.ListenerTest" name="testSkip" time="0.001">
    <skipped/>
  </testcase> <!-- testSkip -->
</testsuite> <!-- Listeners -->
