<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H5MG9OP" failures="1" tests="4" name="Test" time="0.07" errors="0" timestamp="2022-01-30T01:35:54 IST">
  <testcase classname="testNGTests.Test1" name="addition" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [51] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [51] but found [50]
at testNGTests.Test1.addition(Test1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addition -->
  <testcase classname="testNGTests.Test1" name="multiplication" time="0.001"/>
  <testcase classname="testNGTests.Test1" name="division" time="0.001"/>
  <testcase classname="testNGTests.Test1" name="subtraction" time="0.0">
    <skipped/>
  </testcase> <!-- subtraction -->
</testsuite> <!-- Test -->
